---
title: "Glossary of Common Terms"
bibliography: references.bib
---


<details><summary>  </summary>

</details>

<details><summary> Operation/action on a set/object/module </summary>

Let $G$ be a group and let $S$ be a set. An operation or
an action of $G$ on $S$ is a homomorphism
$$\pi: G \to \text{Perm}(S)$$
of $G$ into the group of permutations of $S$.
We then call $S$ a $G$-set. 
We denote the permutation associated with an element 
$x \in G$ by $\pi_x$. Thus the homomorphism is denoted by
$x \mapsto \pi_x$.
That is,
$$
\pi_{g_1 g_2} = \pi_{g_1} \circ \pi_{g_2} \in \text{Perm}(S).
$$
Given $s \in S$, the image of $s$ under the permutation 
$\pi_x$ is $\pi_x(s)$. From such an operation 
we obtain a mapping
$$G \times S \to S$$
$$G \times S \ni (x,s) \mapsto \pi_x(s) =: xs \in S.$$

</details>

<details><summary> Algebra </summary>
p. 121 @LangAlgebra.

Let $A$ be a commutative ring. 
Let $E$, $F$ be modules. 
By a bilinear map 
$$g: E \times E \to F$$
we mean a map such that 
given $x \in E$, the map 
$g(x, \cdot)$ is $A$-linear: 
$$
g(x,y_1+y_2) = g(x,y_1) + g(x, y_2)
$$
for all $y_1, y_2 \in E$ 
(additive group homomorphism)
and 
$$
g(x,a y_1) = a g(x, y_1),
$$
for all $a \in A$ and $y_1 \in E$,
and given $y \in E$, the map 
$g(\cdot, y)$ is also $A$-linear.

By an $A$-algebra, we mean 
a module $E$ together with a bilinear map 
$g: E \times E \to E$. 
We view such a map as a law of composition on $E$.

We note that the group ring $A[G]$ (or monoid ring when $G$ is a monoid)
is an $A$-algebra, also called the group (or monoid) algebra. 
Actually the group algebra can be viewed as a special 
case of the following situation. 

Let $f: A \to B$ be a ring homomorphism such that $f(A)$
is contained in the center of $B$, i.e., 
$f(a)$ commutes with every element of $B$ for every $a \in A$.
Then we may view $B$ as an $A$-module (how?), defining
the operation of $A$ on $B$ by the map 
$$(a,b) \mapsto f(a)b$$
for all $a \in A$ and $b \in B$.
The axioms for a module are trivially satisfied (why?), and the 
multiplicative law of composition $B \times B \to B$ (what is this? $B$
is a-priori a ring, so it is just the multiplicative law)
is clearly bilinear (i.e. $A$-bilinear). In this book, unless otherwise
specified, by an algebra over $A$, we shall always mean a ring
homomorphism as above. We say that the algebra is finitely-generated
if $B$ is finitely generated as a ring over $f(A)$.


A non-commutative, non-associative algebra is one for which 
the law of composition $g$ is non-commutative: 
$g(e_1, e_1) \ne g(e_2,e_1)$ for some $e_1,e_2 \in E$, 
and for which the law of composition $g$ is also not
associative: 
$g(g(e_1,e_2),e_3) \ne g(e_1, g(e_2,e_3))$
for some $e_1, e_2, e_3 \in E$.

</details>





<details><summary> Module, Submodule </summary>

Let $A$ be a ring. 
A left-module over $A$, denoted by $M$, 
is an abelian group, usually written
additively, together with an operation
of $A$ on $M$ (viewing $A$ as a multiplicative monoid 
by R2), such that, 
for all $a,b \in A$ and $x,y \in M$, 
we have 
$(a+b)x = ax + bx$ and $a(x+y) = ax + ay$.

One can prove that 
$a(-x) = -(ax)$ and that $0x = 0$.
By definition of an operation, we
have $1x = x$. 

Let $M$ be a module. By a submodule $N$ of $M$ we mean an additive
subgroup such that $AN \subset N$. 

</details>


<details><summary> Vector Space </summary>

A vector space $V$ is a module $V$ over a field $\mathbb F$. 

</details>


<details><summary> Free Module </summary>

A free module $M$ is a module which admits a basis
or the zero module.

A vector space is always free.

</details>


<details><summary> Ring </summary>

#### Basic Definition

p.83 @LangAlgebra.

A Ring $A$ is a set, together with 
two laws of composition called multiplication 
and addition respectively, 
and written as a product and as a sum respectively, 
satisfying the following conditions

(R1) With respect to addition, $A$ is a commutative group.

(R2) The multiplication is associative, and has a unit element.

(R3) For all $x,y,z \in A$, we have 
$(x+y)z = xz + yz$ and $z(x+y) = zx + zy$. This is called distributivity.

We denote the unit element for addition by $0$ and 
the unit element for multiplication by $1$.

We say $A$ is commutative if $xy = yx$ for all $x,y \in A$.

#### Ring Homomorphism

p.88 @LangAlgebra

By a ring-homomorphism, one means a mapping $f: A \to B$
where $A$, $B$ are rings, and such that $f$ is a monoid-homomorphism
for the multiplicative structures on $A$ and $B$ and 
also a monoid-homomorphism for the additive structure. 


</details>


<details><summary> Convolution Product </summary>

Page 85 Lang Algebra.

</details>


<details><summary> Universal Objects </summary>

Let $\mathfrak{C}$ be a category. An object $P$ of 
$\mathfrak{C}$ is called universally attracting if there
exists a unique morphism of each object of 
$\mathfrak{C}$ into $P$, and is called
universally repelling if for every object of 
$\mathfrak{C}$ there exists a unique morphism of $P$ 
into this object. 

When the context is clear, we call objects $P$
as above universal. Since a universal object 
$P$ admits the identity morphism into itself, 
it is clear that if $P$, $P'$ are two universal objects
in $\mathfrak{C}$, then there exists a unique isomorphism 
between them.

</details>

<details><summary> Free abelian group generated by $S$ </summary>
Page 38 Lang. 

Let $S$ be a set. 
We shall define the abelian group generated by
$S$ as follows. Let $\mathbb Z\langle S \rangle$
be the set of maps 
$\phi: S \to \mathbb Z$ such that 
$\phi(x) = 0$ for almost all $x \in S$. 
Then $\mathbb Z \langle S \rangle$ 
is an abelian group (addition being the usual addition of maps). 
If $k$ is an integer and $x$ is an element of $S$, 
we denote by $k \cdot x$ the map 
$\phi$ such that $\phi(x) = k$ and 
$\phi(y) = 0$ if $y \ne x$. 
Then it is obvious that every element 
$\phi$ of $\mathbb Z \langle S \rangle$ can be 
written in the form 
$$
\phi = k_1 \cdot x_1 + \cdots + k_n \cdot x_n
$$
for some integers $k_i$ and elements $x_i \in S$
for $i \in [n]$, all the $x_i$ being distinct. 
Furthermore, $\phi$ admits a unique such expression, because if we have 
$$
\phi = \sum_{x \in S}k_x \cdot x = \sum_{x \in S} k_x' \cdot x
$$
then $0 = \sum_{x \in S} (k_x - k_x') \cdot x$,
whence
$k_x' = k_x$ for all $x \in S$. 
We map $S$ into $\mathbb Z \langle S \rangle$ 
by the map 
$f_S = f$ such that $f(x) = 1 \cdot x$. 
It is then clear that $f$ is injective, 
and that $f(S)$ generates $\mathbb Z \langle S \rangle$. 
If $g: S \to B$ is a mapping of $S$ into some abelian group $B$, 
then we can define a map
$$
g_*: \mathbb Z \langle S \rangle \to B
$$
such that 
$$
g_* \left( \sum_{x \in S} k_x \cdot x \right) = \sum_{x \in S} k_x g(x).
$$
This map is a homomorphism (trivial) and we have $g_* \circ f = g$ (also trivial). 
It is the only homomorphism 
which has this property, for any such 
homomorphism $g_*$ must be such that $g_*(1 \cdot x) = g(x)$. 

It is customary to identify
$S$ in $\mathbb Z(S)$, 
and we sometimes omit the dot 
when we write 
$k_x x$ or a sum $\sum k_x x$. 

If $\lambda: S \to S'$ is a mapping of sets, 
there is a unique homomorphism
$\overline{\lambda}$ making a certain diagram commutative. 
The diagram implements the relation
$$
\overline{\lambda} \circ f_S = f_{S'} \circ \lambda,
$$
where
$$f_S: S \to \mathbb Z \langle S \rangle,$$ 
$$f_{S'}: S' \to \mathbb Z \langle S' \rangle,$$
$$\lambda: S \to S',$$
$$\overline{\lambda}: \mathbb Z \langle S \rangle \to \mathbb Z \langle S \rangle.$$

In fact $\overline{\lambda}$ is none other than $(f_{S'} \circ \lambda)_*$, with 
the notation of the preceding 
paragraph. The proof of this statement is a trivial exercise. 

We shall denote $\mathbb Z \langle S \rangle$ also by 
$F_{ab}(S)$, and call $F_{ab}(S)$ the 
free abelian group generated by $S$. 
We call elements of $S$ its free generators. 

As an exercise, show that 
every abelian group $A$ is a factor group
of a free abelian group $F$. 
If $A$ is finitely generated, show that one can select
$F$ to be finitely generated also. 

If the set $S$ consists of $n$ elements, 
then we say that the free abelian 
group $F_{ab}(S)$ is the free abelian group on $n$ generators. 
If $S$ is the set of $n$ letters
$x_1, \cdots, x_n$, we say that $F_{ab}(S)$
is the free abelian group with free generators
$x_1, \cdots, x_n$. 

An abelian group is free if and only if it is
isomorphic to a free abelian group
$F_{ab}(S)$ for some set $S$. 
Let $A$ be an abelian group, and let $S$ be a basis for $A$. 
Then it is clear that $A$ is isomorphic 
to the free abelian group $F_{ab}(S)$.


</details>

<details><summary> Group $G$ generated by a set $S$ </summary>

Let $G$ be a group and $S$ a subset of $G$. 
We say that 
$S$ generates $G$, or that $S$ is a set of generators of $G$, 
if every element of $G$ can be expressed
as a product of elements of $S$ 
or inverses of elements of $S$, i.e., as a 
product 
$x_1 \cdots x_n$ where each $x_i$ or $x_i^{-1}$ is in $S$.
The set of all such products 
is a subgroup of $G$ (the empty product is the unit element), 
and is the smallest 
subgroup of $G$ containing $S$. Thus $S$ generates $G$ 
if and only if 
the smallest subgroup 
of $G$ containing $S$ is $G$ itself. 
If $G$ is generated by $S$, we write $G = \langle S \rangle$. 

</details>

<details><summary> Monoid, submonoid </summary>

A monoid is a set $G$, with a law of composition
which is associative, and having a unit element 
(so that in particular $G$ is non-empty).
A law of composition is just a map
$G \times G \ni (x,y) \mapsto xy \in G$
which is denoted multiplicatively as above, 
or additively, as in 
$G \times G \ni (x,y) \mapsto x+y \in G$. 
An element $e \in G$ such that 
$ex = xe = x$ for all $x \in G$ is called a unit 
element. A unit element is unique. 
When the law of composition is additive, then we
write $0 \in G$ for the unit element. 
Given $x,y,z \in G$, the product of these
elements can be formed in two ways $(xy)z$ and 
$x(yz)$. $G$ being associative means these
two ways produce the same element in $G$.

A submonoid $H$ of $G$ is a subset
of $G$ containing the unit element
and which is closed under the law of composition. 
That is, $x,y \in H$ implies that $xy \in H$. 
$H$ is itself a monoid under the law
of composition induced by $G$, i.e. the restriction 
to $H \times H \to H$.

</details>

<details><summary> Group, subgroup </summary>

A group $G$ is a monoid (set, law of composition is associative, and there is a unit element)
such that every element $x \in G$ has an inverse
$x^{-1} \in G$. That is, if $x \in G$, then $xx^{-1} = x^{-1}x = e$.

A subgroup $H$ of $G$
is a subset of $G$ which is closed
under taking inverses and the law of composition, and contains the unit element.

</details>

<details><summary> Group Homomorphism, Isomorphism, Automorphism, Endomorphism </summary>

p.10 @LangAlgebra.

Let $G, G'$ be monoids.
A homomorphism is a mapping 
$f: G \to G'$ such that 
$f(xy) = f(x)f(y)$ for all $x,y \in G$
and the identity of $G$ is mapped to the 
identity of $G'$.
If in addition $G, G'$ are groups, 
then $f$ is called a group homomorphism.

A homomophism $f: G \to G'$ is called an isomorphism
if there exists a homomorphism $g: G' \to G$ such that 
$f \circ g$ and $g \circ f$ are the identity mappings
(in $G'$ and $G$ respectively).

An isomorphism $f: G \to G$ is called 
an automorphism. 

A homomorphism of $G$ into itself is called an endomorphism. 

</details>

<details><summary> Left/right coset </summary>

p. 12 Lang

Let $G$ be a group and let $H$ be a subgroup. 
A left coset of $H$ in $G$ is a subset 
of $G$ of type $aH$, for some element
$a$ of $G$. An element of $aH$ is called a coset 
representative of $aH$. The map $x \mapsto ax$ induces
a bijection of $H$ onto $aH$. 
Hence any two left cosets have the same cardinality. 

Observe that if $a,b$ are elements in $G$
and $aH$, $bH$ are cosets having one element 
in common, then they are equal. Indeed, let $ax = by$ with $x,y \in H$.
Then $a = byx^{-1}$. But $yx^{-1} \in H$. Hence, $aH = b(yx^{-1})H = bH$, because 
for any $z \in H$ we have $zH = H$.

We conclude that $G$ is the disjoint union of the left cosets of $H$. 
A similar remark applies to the right cosets (subsets of $G$ of type $Ha$).

</details>

<details><summary> Factor Ring </summary>

p.89 Lang

Let $\mathfrak{a}$ be an ideal of the ring $A$. 
We can construct the factor ring $A/\mathfrak{a}$
as follows. Viewing $A$ and $\mathfrak{a}$ as additive
groups, let $A/\mathfrak{a}$ be the factor group. 
We define a multiplicative law of composition on $A/\mathfrak{a}$: 
If $x + \mathfrak{a}$ and $y + \mathfrak{a}$ are two cosets
of $\mathfrak{a}$, we define $(x + \mathfrak{a})(y+\mathfrak{a})$
to be the coset $(xy+ \mathfrak{a})$. This coset is well-defined, 
for if $x_1, y_1$ are in the same coset as $x,y$ respectively, 
then one verifies at once that $x_1y_1$ is in the same coset as $xy$. 

p.91

The factor ring $A/\mathfrak{a}$ is also called a residue class ring. 
Cosets of $\mathfrak{a}$ in $A$ are called residue classes modulo 
$\mathfrak{a}$, and if $x \in A$, then the coset $x + \mathfrak{a}$
is called the residue class of $x$ modulo $\mathfrak{a}$.


</details>

<details><summary> Factor module </summary>
p. 119 Lang

Let $M$ be an $A$-module, and $N$ a submodule. 
We shall define a module structure on the factor group
$M/N$ (for the additive group structure).
Let $x + N$ be a coset of $N$ in $M$, and let $a \in A$.
We define $a(x+N)$ to be the coset $ax + N$. 
It is trivial to verify that this is well-defined (i.e. 
if $y$ is in the same coset as $x$, then $ay$ is in 
the same coset as $ax$), and that this is an operation of $A$
on $M/N$ satisfying the required condition, making $M/N$
into a module, called the factor module of $M$ by $N$. 

</details>

<details><summary> Factor group </summary>
p. 14 Lang

Let $f: G \to G'$ be a group homomorphism,
and let $H$ be its kernel. If $x$ is an element of $G$,
then $xH = Hx$ because both are equal to 
$f^{-1}(f(x))$. We can also rewrite this relation
as $xHx^{-1} = H$. 

Conversely, let $G$ be a group, and let $H$ be a subgroup. 
Assume that for all elements $x$ of $G$ we have 
$xH \subset Hx$ (or equivalently $xHx^{-1} \subset H$). 
If we write $x^{-1}$ instead of $x$, we get
$H \subset xHx^{-1}$, whence $xHX^{-1} = H$. 
Thus our condition is equivalent to the condition 
$xHx^{-1} = H$ for all $x \in G$. 
A subgroup $H$ satisfying this condition
will be called normal. We shall now see that a normal 
subgroup is the kernel of a homomorphism. 

Let $G'$ be the set of cosets of $H$. (By assumption, 
a left coset is equal to a right coset, so we need not
distingush between them.) If $xH$ and $yH$ are cosets, 
then their product $(xH)(yH)$ is also a coset, because
$$xHyH = xyHH = xyH.$$

By means of this product, we have defined 
a law of composition on $G'$ which is associative. 
It is clear that the coset $H$ itself is a unit element
for this law of composition, and that $x^{-1}H$ is an inverse for the
coset $xH$. Hence, $G'$ is a group. 

Let $f: G \to G'$ be the mapping such that 
$f(x)$ is the coset $xH$. Then $f$ is clearly
a homomorphism, and (the subgroup) $H$ is contained
in its kernel. If $f(x) = H$, then $xH = H$. Since $H$ contains the 
unit element, it follows that $x \in H$. Thus $H$ is equal to 
the kernel, and we have obtained 
our desired homomorphism. 

The group of cosets of a normal subgroup $H$ is denoted by $G/H$
(which we read $G$ modulo $H$, or $G \mod H)$. The map
$f$ of $G$ onto $G/H$ constructed above
is called the canonical map, and $G/H$ is called the factor group
of $G$ by $H$.

</details>

<details><summary> Free Module over a ring $A$ generated by a non-empty set $S$ </summary>
p. 137 Lang

We let $A\langle S \rangle$ be the set of functions
$\phi: S \to A$ such that $\phi(x) = 0$ for almost all $x \in S$.
If $a \in A$ and $x \in S$, we denote by
$ax$ the map $\phi$ such that $\phi(x) = a$ and $\phi(y) = 0$
for $y \ne x$. Then as for abelian groups, given 
$\phi \in A \langle S \rangle$, there exists elements $a_i \in A$
and $x_i \in S$ such that 
$$\phi = a_1x_1 + \cdots + a_n x_n.$$
It is immediately verified that 
the family of functions $\delta_x$ $(x \in S)$ such that
$\delta_x(x) = 1$ and $\delta_x(y) = 0$ for all
$y \ne x$ form a basis for $A \langle S \rangle$.
In other words, the expression of $\phi$ as
$\sum a_i x_i$ above is unique. This construction can be applied
when $S$ is a group or a monoid $G$, and gives rise to the group 
algebra.

So $A \langle S \rangle$ is the free module over the ring $A$ generated by $S$.

</details>

<details><summary> Category </summary>
p. 53 Lang

A category $\mathfrak C$ consists of a collection 
of objects $\text{Ob}(\mathfrak C)$; and for two objects
$A,B \in \text{Ob}( \mathfrak C)$ a set $\text{Mor}(A,B)$
called the set of morphisms of $A$ into $B$;
and for three objects $A,B,C \in \text{Ob}(\mathfrak C)$ a law of composition (i.e. a map)
$$\text{Mor}(B,C) \times \text{Mor}(A,B) \to \text{Mor}(A,C)$$
satisfying 
the following axioms

(Cat 1) Two sets $\text{Mor}(A,B)$ and $\text{Mor}(A',B')$ are disjoint 
unless $A = A'$ and $B = B'$, in which case they are equal. 

(Cat 2) For each object $A$ of $\mathfrak C$ there is a morphism
$\text{id}_A \in \text{Mor}(A,A)$ which acts
as left and right identity for the elements 
$\text{Mor}(A,B)$ and $\text{Mor}(B,A)$ respectively,
for all objects $B \in \text{Ob}(\mathfrak C)$.

(Cat 3) The law of composition is associative (when defined), i.e.
given $f \in \text{Mor}(A,B)$, $g \in \text{Mor}(B,C)$ and $h \in \text{Mor}(C,D)$
then 
$$(h \circ g) \circ f = h \circ (g \circ f),$$
for all objects
$A,B,C,D$ of $\mathfrak C$.

</details>

<details><summary> Isomorphism, automorphism, endomorphism in Categories </summary>
p. 54 Lang

An element $f \in \text{Mor}(A,B)$ is also written
$f: A \to B$ or 
$$A \xrightarrow{f} B.$$
A morphism $f$ is called an isomorphism if there exists
a morphism $g: B \to A$ such that $g \circ f$ and $f \circ g$ are the identities
in $\text{Mor}(A,A)$ and $\text{Mor}(B,B)$ respectively. 
If $A = B$, then we also say that the 
isomorphism is an automorphism. 

A morphism of an object $A$ into itself is called an 
endomorphism. The set of endomorphisms of $A$ is denoted by
$\text{End}(A)$. It follows at once from our axioms that 
$\text{End}(A)$ is a monoid.

Let $A$ be an object of a category $\mathfrak C$.
We denote by $\text{Aut}(A)$ the set of automorphisms
of $A$. 

</details>

<details><summary> Direct Product </summary>
p. 9 Lang.

Let $G_1, G_2$ be groups. 
Let $G_1 \times G_2$ be the direct product as sets, 
so $G_1 \times G_2$ is the set of all pairs
$(x_1, x_2)$ with $x_i \in G_i$. We define the product 
componentwise by
$$(x_1, x_2)(y_1,y_2) = (x_1y_1, x_2y_2).$$
Then $G_1 \times G_2$ is a group, whose unit element
is $(e_1, e_2)$ (where $e_i$ is the unit element of $G_i$.)
Similarly, for $n$ groups we define 
$G_1 \times \cdots G_n$ to be the set of $n$-tuples
with $x_i \in G_i$ ($i=1,\cdots,n$), 
and componentwise multiplication. 
Even more generally, 
let $I$ be a set, and for each $i \in I$, let $G_i$ be a group. 
Let $G = \prod G_i$ be the set theoretic product
of the sets $G_i$. Then $G$ is the set of all 
families $(x_i)_{i \in I}$ with $x_i \in G_i$. 
We can define a group structure on $G$ 
by componentwise multiplication, namely, if $(x_i)_{i \in I}$
and $(y_i)_{i \in I}$ are two elements of $G$, 
we define their product
to be $(x_iy_i)_{i \in I}$. 
We define the inverse of $(x_i)_{i \in I}$ to be $(x_i^{-1})_{i \in I}$. 
It is then obvious that $G$ is a group 
called the direct product
of the family. 

</details>

<details><summary> Direct Sum </summary>

p. 36 Lang.

Let $(A_i)_{i \in I}$ be a family of abelian groups. 
We define their direct sum 
$$A = \bigoplus_{i \in I} A_i$$
to be the subset of the direct product
$\Prod A_i$ consisting of all the families 
$(x_i)_{i \in I}$ with 
$x_i \in A_i$ such that $x_i = 0$ for all but a finite number of indices $i$. 
Then it is clear that $A$ is a subgroup
of the product. For each index $j \in I$, we map
$$\lamba_j: A_j \to A$$
by letting 
$\lambda_j(x)$ be the element whose $j$-th component is $x$, 
and having all other components equal to $0$. 
Then $\lambda_j$ is an injective homomorphism. 

Proposition 7.1. Let $\{f_i: A_i \to B\}$ be a family of homomorphisms
into an abelian group $B$. Let $A = \bigoplus A_i$. There exists
a unique homomorphism
$$f: A \to B$$
such that 
$f \circ \lambda_j = f_j$ for all $j$.

Proof. Define $f: A \to B$ 
by 
$$
f((x_i)_{i \in I}) = \sum_{i \in I} f_i(x_i), 
$$
and argue accordingly. q.e.d.

The property in Prop 7.1 is called the 
universal property of the direct sum. 

p.37 Lang

Let $A$ be an abelian group
and $B,C$ subgroups. If $B+C = A$
and $B \cap C = \{0\}$ then the map 
$$B \times C \to A$$
given by
$(x,y) \mapsto x+y$
is an isomorphism (as we already noted in the non-commutative case).
Instead of writing 
$A = B \times C$, 
we shall write
$$A = B \oplus C$$
and say that $A$ is the direct sum 
of $B$ and $C$. We use a similar notation
for the direct sum 
of a finite number 
of subgroups $B_1, \cdots, B_n$ such that 
$$B_1 + \cdots + B_n = A$$
and $$B_{i+1} \cap (B_1 + \cdots + B_i) = 0.$$
In that case we write
$A = B_1 \oplus \cdots \oplus B_n.$


</details>


<details><summary> Graded Algebra </summary>

p. 172 Lang.

Let $A$ be an algebra over a field $k$. 
By a filtration of $A$ we mean 
a sequence of $k$-vector spaces
$A_i$ $(i=0,1,\cdots)$ such that 
$$
A_0 \subset A_1 \subset A_2 \subset \cdots
$$
and 
$$\cup A_i = A,$$
and $A_iA_j \subset A_{i+j}$
for all $i,j \ge 0$.
In particular, $A$ is an $A_0$-algebra (why?). 
We then call
$A$ a filtered algebra. Let $R$ 
be an algebra. 
We say that $R$ is graded if
$R$ is a direct sum 
$R = \bigoplus R_i$ of subspaces
such that
$R_iR_j \subset R_{i+j}$ for all
$i,j \ge 0$.


(Note that $A_iA_j$ uses the 
$k$-bilinear form in the definition of the $k$-algebra $A$.)
</details>

<details><summary>Basis  </summary>

p.38 Lang. 

Let $A$ be an abelian
group. Let $\{e_i\}_{i \in I}$
be a family of elements of $A$. 
We say that this family is a basis 
for $A$ if the family is not empty, and if every 
element of $A$ has a unique expression 
as a linear combination
$$x = \sum x_ie_i$$
with $x_i \in \mathbb Z$, 
and almost all $x_i = 0$. Thus the sum 
is actually a finite sum. An abelian group
is said to be free if it has a basis. 
If that is the case, it is immediate that
if we let $Z_i = \mathbb Z$ for all $i \in I$, 
then $A$ is isomorphic to the direct sum
$$A \cong \bigoplus_{i \in I} A_i.$$

p. 135 Lang.

Let $M$ be a module over a ring $A$
and let $S$ be a subset of $M$. 
We shall say that $S$ is a basis of $M$
if $S$ is not empty, if $S$ generates $M$, and if 
$S$ is linearly independent. 
If $S$ is a basis of $M$, then in particular
$M \ne \{0\}$ if $A \ne \{0\}$ 
and every element of $M$ has a unique expression
as a linear combination of elements of $S$. Similarly, let 
$\{x_i\}_{i \in I}$ be a non-empty family
of elements of $M$. We say that it is a basis
of $M$ if it is linearly independent and generates $M$.

</details>

<details><summary> Dual Space and Dual Module </summary>

p. 142 Lang

Let $E$ be a free module over a commutative ring $A$. 
We view $A$ as a free module of rank 1 over itself. By
the dual module $E^\vee$ of $E$ we shall mean the module
$\text{Hom}(E,A)$. Its elements will be called functionals.
Thus a functional on $E$ is an $A$-linear map
$f: E \to A$. If $x \in E$ and $f \in E^\vee$, we sometimes denote
$f(x)$ by $\langle x, f \rangle$. Keeping $x$ fixed, we see that the symbol
$\langle x, f \rangle$ as a function of $f \in E^\vee$ is $A$-linear
in its second argument, and hence that $x$ induces a linear map
on $E^\vee$, which is $0$ if and only if $x = 0$. 
Hence we get an injection $E \to E^{\vee \vee}$ which is not always an
injection. 

Let $(x_i)_{i \in I}$ be a basis of $E$. 
For each $i \in I$, let $f_i$ be the unique functional such that 
$f(x_i) = \delta_{ij}$. Such a linear map exists by general properties
of bases. 

Theorem 6.1. Let $E$ be a finite free module over the commutative ring
$A$, of finite dimension $n$. Then $E^\vee$ is also free, and
$\dim E^\vee = n$. If $\{x_1, \cdots, x_n\}$ is a basis for $E$, 
and $f_i$ is the functional such that $f_i(x_j) = \delta_{ij}$, then
$\{f_1, \cdots, f_n\}$ is a basis for $E^\vee$. 

Proof. Show that the $f_i$ generate the dual space 
and are linearly independent in the dual space. Be careful, 
$f_i$ is only the indicator function on the basis $x_i$, 
but scales appropriately. q.e.d.

</details>

<details><summary> Ideal </summary>

p. 86 Lang. 

A left ideal $\mathfrak{a}$ in a ring $A$ is a subset of $A$ which 
is a subgroup of the additive group of $A$, such that
$A \mathfrak{a} \subset \mathfrak{a}$ and hence 
$A \mathfrak{a} = A$, since $A$ contains $1$).
To define a right ideal, we require $\mathfrak{a}A = \mathfrak{a},$
and a two-sided ideal is a subset which is both a left and a right ideal. 
A two-sided ideal is called simply an ideal in this section. 


A ring $A$ is said to be commutative if $yx = xy$ for all $x,y \in A$. 
In that case, every left or right ideal is two-sided.

</details>

