---
title: "'Tis the Yang-Mills Lattice"

bibliography: references.bib

# format:
#   html:
#     code-fold: true
# jupyter: python3
---

::: {.hidden}
$$
\newcommand\mcy{{\mathcal{Y}}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\C}{\mathbb{C}}
\newcommand{\Tr}{\text{Tr}}
\def\*#1{\mathbf{#1}}
$$
:::

## June 14, 2026

We want to show that
$\lVert H_i \rVert \le \eta$ for all
$i \in [3]$
implies that
$|\Tr(H_1H_2H_3)| < \eta^3.$

**Lemma**. *The function 
$\langle A, B \rangle = \Tr (A^*B)$
defines an inner product on 
the $\R$ or $\C$ vector space $\C^{N \times N}$.*

Proof.
Let us consider first $\C^{N \times N}$ as a $\C$ vector space.
We leave the $\R$ proof for another life.
Let us check the axioms in definition 2.1 on page 9 of @Alt2012, 
except that we will use anti-linearity in the first slot (the physicist's
convention).

Let $\alpha \in \C$ and consider $A, B \in \C^{N \times N}$.
We have 
$$\langle \alpha A, B \rangle = \Tr((\alpha A)^* B) = \alpha^* \Tr(A^* B) = \alpha^* \langle A, B \rangle.$$

We also have
$$\langle A, \alpha B \rangle = \Tr((A^* (\alpha B)) = \alpha \langle A, B \rangle.$$

And if $A,B,C \in \C^{N \times N}$, we have
$$\langle A + C, B \rangle = \Tr((A+C)^* B) = \Tr(A^*B + C^*B) = \Tr(A^*B) + \Tr(C^*B) = \langle A, B \rangle + \langle C, B \rangle.$$

Similarly, 
$$\langle A, C+B \rangle = \langle A, B \rangle + \langle A, C \rangle.$$
Up to this point we have shown that 
$\langle \, \cdot \, , \, \cdot \, \rangle$ is a sesequilinear form.

Next, for $A, B \in \C^{N \times N}$, we have
\begin{equation*}
    \begin{aligned}
        \overline{\langle A, B \rangle} = \overline{\Tr(A^*B)} = \sum_{i=1}^N \overline{(A^*B)_{ii}} \\
        = \sum_{i=1}^N \sum_{j=1}^N \overline{(A^*)_{ij} B_{ji}}
        = \sum_{i=1}^N \sum_{j=1}^N \overline{\overline{(A_{ji})} B_{ji}} \\
        = \sum_{i=1}^N \sum_{j=1}^N (A_{ji}) \overline{B_{ji}}
        = \sum_{i=1}^N \sum_{j=1}^N (B^*)_{ij} (A_{ji})  \\
        = \sum_{i=1}^N (B^* A)_{ii} = \Tr(B^*A) = \langle B, A \rangle,
    \end{aligned}
\end{equation*}
which shows symmetry.

Next, for $A \ne 0 \in \C^{N \times N}$, we have
\begin{align*}
    \langle A, A \rangle = \Tr(A^* A) = \sum_{i,j=1}^N \lVert A_{ij} \rVert^2 > 0.
\end{align*}
Since $\langle 0, 0 \rangle = 0$, 
this shows that $\langle \, \cdot \, , \, \cdot \, \rangle$ 
is positive definite. 
Therefore $\langle \, \cdot \, , \, \cdot \, \rangle$ defines
an inner product on $\C^{N \times N}$. QED.

**Lemma**. *Let $X_1, \cdots, X_k$ be $k$ matrices in $\C^{N \times N}$.
Then 
$$|\Re \Tr X_1 \cdots X_k| \le \lVert X_1 \rVert \cdots \lVert X_k \rVert,$$
where $\lVert \, \cdot \, \rVert$ denotes the Hilbert Schmidt norm 
induced by the inner product $\langle A ,B \rangle = \Tr(A^*B)$ defined in the above lemma.*

Proof. QED.

**Assumptions for the following lemmas.**
    *Let $p \in \mathcal{P}(\Lambda_n)$ be a plaquette.
    Let $U \in \mathrm{U}(N)^{E_n}$ be a unitary configuration. 
    Let $U_1 = U_{p_1}$, $U_2 = U_{p_2}$, $U_3= U_{p_3}$, and $U_4 = U_{p_4}$.
    Suppose $H_1, H_2, H_3, H_4 \in \mathrm{H}(N)$ satisfy
    $e^{iH_1} = U_{p_1}$, $e^{iH_2} = U_{p_2}$, $e^{iH_3} = U_{p_3}$, 
    and $e^{iH_4} = U_{p_4}$.
    Suppose that 
    $$
    H_p = H_1 + H_2 - H_3 - H_4.
    $$
    Let
    \begin{equation}
        \begin{aligned}
            R_1 &= I + iH_1 - H_1^2/2 \\
            R_2 &= I + iH_2 - H_2^2/2 \\
            R_3 &= I - iH_3 - H_3^2/2 \\
            R_4 &= I - iH_4 - H_4^2/2 \\
        \end{aligned}
    \end{equation}
    and suppose 
    $$
    R_p = R_1R_2R_3R_4.
    $$
    Suppose that $\lVert H_i \rVert \le \eta \le 1$ for all $i = 1, 2, 3, 4$.
    Suppose also that $\phi(X) = \Re \Tr (I - X)$ for any $X \in \C^{N \times N}$.*

**Lemma**. 
    *We have
    $$
    \left|\frac{1}{2} \lVert H_p \rVert^2 - \phi(R_p) \right| \le C \eta^3,
    $$
    where the constant $C > 0$ depends only on $N$.*

Proof. 

**Lemma**.
    *We have 
    $$
    \left| \phi(U_p) - \frac{1}{2} \lVert H_p \rVert^2 \right| \le C \eta^3,
    $$
    where the constant $C > 0$ depends only on $N$.*

Proof. 

## June 10, 2026

:::{#lem-symmetric-bilinear-form}
Let $\mathrm{H}(N)$ be the set of Hermitian matrices equipped
with $\R$-scalar multiplication and matrix addition, turning it
into an $\R$-vector space. Then the function 
$$(H,R) \mapsto \Re (\Tr(H^*R))$$
defines a symmetric bilinear form on $\mathrm{H}(N)$.
:::

Let $E_n^1 \subset E_n$.
Let $(\mathrm{H}(N))^{E_n^1}$ be the set of all 
Hermitian configurations. 

:::{#lem-hermitian-configs-as-R-vec-space}
Under pointwise addition and pointwise $\R$ scalar
multiplication, $(\mathrm{H}(N))^{E_n^1}$ becomes 
an $\R$ vector space. 
:::

Proof. 
Let $H, R \in (\mathrm{H}(N))^{E_n^1}$. Then 
$(H + R)_e = H_e + R_e \in \mathrm{H}(N)$.
The zero element is the Hermitian configuration 
with all zero matrices on the edges. 
The additive inverse of a given configuration is
just the additive inverse on each edge. 
And scalar multiplication is defined as follows: 
$\lambda H = (\lambda H_e)_{e \in E_n^1}$.
QED.

:::{#lem-hermitian-configs-bilinear-form}
The function 
$$
(H, R) \mapsto \sum_{p \in \mathcal{P}(\Lambda_n)} \Re (\Tr(H_p^*R_p))
$$
where $H_p = H_{p_1} + H_{p_2} - H_{p_3} - H_{p_4}$
defines a symmetric bilinear form 
$M_{H}: \mathrm{H}(N)^{E_n^1} \times \mathrm{H}(N)^{E_n^1} \to \R$.
:::

:::{#lem-hermitian-configs-pos-def-quad-form}
The diagonal of $M_H$, also denoted by $M_H$, defined by
$$
\mathrm{H}(N)^{E_n^1} \ni R \mapsto M_H(R, R)
$$
is a positive definite quadratic form. 
In particular, 
$$
e^{-\frac{1}{2}M_H(R)} \prod_{e \in E_n^1} d\lambda(R_e)
$$
defines a Gaussian measure on $\mathrm{H}(N)^{E_n^1}.$
:::

Let us define 
$$
\langle H, R \rangle_{\mathrm{H}(N)^{E_n^1}} = \sum_{e \in E_n^1} \Re ( \Tr (H_e^* R_e)).
$$
Then there ought to exist 
some mathematical object $L$ such that 
$$
\langle H, LR \rangle_{\mathrm{H}(N)^{E_n^1}} = M_H(H, R)
$$
for all $H, R \in \mathrm{H}(N)^{E_n^1}$.

Let $t_{i, e} \in \R^{N^2|E_n^1|}$.

Consider the map 
$$
\R^{N^2|E_n^1|} \times \R^{N^2|E_n^1|} \ni (t_{i, e}, s_{i, e}) \mapsto
\sum_{i=1}^{N^2} \sum_{p \in \mathcal{P}(B_n)} t_{i,p} s_{i,p} \in \R
$$
where $t_{i,p} = t_{i,p_1} + t_{i,p_2} - t_{i,p_3} - t_{i,p_4}$
for any $i \in [N^2]$.
Let's call this map $M_{\R^{N^2|E_n^1|}}$.
Calling it's diagonal by the same name, then
$$
e^{-\frac{1}{2} M_{\R^{N^2|E_n^1|}} (X)} \prod_{i=1}^{N^2} \prod_{e \in E_n^1} dl{X_{i,e}}
$$
defines a Gaussian measure on $\R^{N^2|E_n^1|}$.
This measure is equal to 
the product measure
$$
\bigotimes_{i=1}^{N^2} \tau_n,
$$
where $\tau_n$ denotes the lattice Maxwell measure on $\R^{|E_n^1|}$.

## June 4, 2026

### Notes on Chapter 14 of Klenke

Lemma 14.7 (@Klenke) 
Let $\emptyset \neq J \subset I$. Then $X_J^I$ is measurable with respect to $\mathcal{A}_I-\mathcal{A}_J$.

Proof. For any $j \in J$, 
$X_j$ is measurable with respect to $\mathcal{A} - \mathcal{A}_j$
by definition of the product $\sigma$ algebra, Definition 14.4.
But $X_j = X_j^J \circ X_J^I$ as functions, 
so therefore we can replace $X_j$ by $X_j^J \circ X_J^I$ in the 
previous sentence. To conclude measurability of 
$X_J^I$, we need to apply the following result of @Klenke: 

Corollary 1.82 (Measurability of composed maps) Let $I$ be a nonempty index set and let $(\Omega, \mathcal{A}),\left(\Omega^{\prime}, \mathcal{A}^{\prime}\right)$ and $\left(\Omega_i, \mathcal{A}_i\right)$ be measurable spaces for any $i \in I$. Further, let $\left(X_i: i \in I\right)$ be a family of measurable maps $X_i: \Omega^{\prime} \rightarrow \Omega_i$ with $\mathcal{A}^{\prime}=\sigma\left(X_i: i \in I \right)$. Then the following holds: A map $Y: \Omega \rightarrow \Omega^{\prime}$ is $\mathcal{A}-\mathcal{A}^{\prime}$-measurable if and only if $X_i \circ Y$ is $\mathcal{A}-\mathcal{A}_i$-measurable for all $i \in I$.

We want to show that $X_J^I$ is measurable with respect to 
$\mathcal{A}_I-\mathcal{A}_J$. Does $\mathcal{A}'$ in the corollary
correspond to $\mathcal{A}_J$? For that we would need that 
$\mathcal{A}_J = \sigma(X_j^J: j \in J)$. Luckily this is
true by inspection of Definition 14.4.
It is easy to see that the conclusion of Corollary 1.82 
corresponds to the conlusion we wanted to obtain. QED.



Definition 14.9 (Cylinder sets @Klenke) For any $i \in I$, let $\mathcal{E}_i \subset \mathcal{A}_i$ be a subclass of the class of measurable sets.

For any $A \in \mathcal{A}_J, X_J^{-1}(A) \subset \Omega$ is called a cylinder set with base $J$. The set of such cylinder sets is denoted by $\mathcal{Z}_J$. In particular, if $A=\prod_{j \in J} A_j$ for certain $A_j \in \mathcal{A}_j$, then $X_J^{-1}(A)$ is called a rectangular cylinder with base $J$. The set of such rectangular cylinders will be denoted by $\mathcal{Z}_J^R$. The set of such rectangular cylinders for which in addition $A_j \in \mathcal{E}_j$ for all $j \in J$ holds will be denoted by $\mathcal{Z}_J^{\mathcal{E}, R}$.

Write
$$
\begin{equation*}
\mathcal{Z}=\bigcup_{J \subset I \text { finite }} \mathcal{Z}_J, \tag{14.3}
\end{equation*}
$$
and similarly define $\mathcal{Z}^R$ and $\mathcal{Z}^{\mathcal{E}, R}$. Further, define
$$
\mathcal{Z}_*^R=\bigcup_{N=1}^{\infty}\left\{\bigcup_{n=1}^N A_n: A_1, \ldots, A_N \in \mathcal{Z}^R\right\}
$$
and similarly $\mathcal{Z}_*^{\mathcal{E}, R}$.

Remark 14.10 Every $\mathcal{Z}_J$ is a $\sigma$-algebra, and $\mathcal{Z}$ and $\mathcal{Z}_*^R$ are algebras. Furthermore, $\bigotimes_{i \in I} \mathcal{A}_i=\sigma(\mathcal{Z})$.

Lemma 14.11. If every $\mathcal{E}_i$ is a $\pi$-system, 
then $\mathcal{Z}^{\mathcal{E}, R}$ is a $\pi$-system.

Proof. First we recall the definition of a $\pi$-system. 
It is a collection of sets $\mathcal{A}$ that is intersection closed, 
meaning that $A \cap B \in \mathcal{A}$ whenever
$A, B \in \mathcal{A}$.
Next, we write down the definition of $\mathcal{Z}^{\mathcal{E}, R}:$
$$
\mathcal{Z}^{\mathcal{E}, R} = \bigcup_{J \subset I \text{ finite}} 
\mathcal{Z}_J^{\mathcal{E}, R}.
$$
An element of the set $\mathcal{Z}^{\mathcal{E}, R}$ is 
some rectangular cylinder set for some base $J$, where
we have the extra requirement involving the $\mathcal{E}_i$.
We take $A, B \in \mathcal{Z}^{\mathcal{E}, R}$.
Then $A \in \mathcal{Z}_J^{\mathcal{E}, R}$ for some base $J \subset I$ which is finite
and $B \in \mathcal{Z}_{J'}^{\mathcal{E}, R}$ for some other base $J' \subset I$
which is also finite.
Furthermore, $A$ is the preimage of 
some cartesian product $\prod_{j \in J} A_j$
under the canonical projection 
$X_J^I: \prod_{i \in I} \Omega_i \to \prod_{j \in J} \Omega_j$. 
In addition, all the $A_j$ must be elements of $\mathcal{E}_j$. 
Likewise, $B$ is the preimage of some cartesian product 
$\prod_{j \in J'} B_j$ under the canonical projection 
$X_{J'}^I: \prod_{i \in I} \Omega_i \to \prod_{j \in J'} \Omega_j$.
As before, we also require that the $B_j$ are elements of $\mathcal{E}_j$.

At this point, we've completely unraveled the definition of the statement
$$
A, B \in \mathcal{Z}^{\mathcal{E}, R}.
$$
Next we explore the definition of the 
set $A \cap B$. For a point $\omega \in \Omega = \prod_{i \in I} \Omega_i$
to be both in $A$ and $B$, we see that $\omega(j) \in A_j$ for all $j \in J$
and $\omega(j) \in B_j$ for all $j \in J'$.
This is only potentially problematic when $j \in J'':= J \cap J'$.
Let's write $C_j := A_j \cap B_j$ for all $j \in J''$.
Next, consider the set 
$$
\left( \prod_{j \in J''} C_j \right) \times
\left( \prod_{j \in J \setminus J''} A_j \right) \times
\left( \prod_{j \in J' \setminus J''} B_j \right).
$$
We see that $A \cap B$ is the preimage 
of the previous set under the canonical 
projection 
$X_{J \cup J'}^I: \prod_{i \in I} \Omega_i \to \prod_{j \in J \cup J'} \Omega_j$
And since the $\mathcal{E}_j$ are $\pi$-systems, we see that
$C_j \in \mathcal{E}_j$ for all $j \in J''$.
Hence, $A \cap B$ is a rectangular cylinder set 
with base $J \cup J'$, which is slightly surprising, 
because I would have thought that $A \cap B$ would have base $J \cap J'$. QED.

Consider now the situation of finitely many $\sigma$-finite measure spaces ( $\Omega_i, \mathcal{A}_i, \mu_i$ ), $i=1, \ldots, n$, where $n \in \mathbb{N}$.

Lemma 14.13 Let $A \in \mathcal{A}_1 \otimes \mathcal{A}_2$ and let $f: \Omega_1 \times \Omega_2 \rightarrow \overline{\mathbb{R}}$ be an $\mathcal{A}_1 \otimes \mathcal{A}_2$ measurable map. Then, for all $\tilde{\omega}_1 \in \Omega_1$ and $\tilde{\omega}_2 \in \Omega_2$,
$$
\begin{aligned}
& A_{\tilde{\omega}_1}:=\left\{\omega_2 \in \Omega_2:\left(\tilde{\omega}_1, \omega_2\right) \in A\right\} \in \mathcal{A}_2 \\
& A_{\tilde{\omega}_2}:=\left\{\omega_1 \in \Omega_1:\left(\omega_1, \tilde{\omega}_2\right) \in A\right\} \in \mathcal{A}_1 \\
& f_{\tilde{\omega}_1}: \Omega_2 \rightarrow \overline{\mathbb{R}}, \quad \omega_2 \mapsto f\left(\tilde{\omega}_1, \omega_2\right) \quad \text { is } \mathcal{A}_2 \text {-measurable }, \\
& f_{\tilde{\omega}_2}: \Omega_1 \rightarrow \overline{\mathbb{R}}, \quad \omega_1 \mapsto f\left(\omega_1, \tilde{\omega}_2\right) \quad \text { is } \mathcal{A}_1 \text {-measurable } .
\end{aligned}
$$

Proof. Let's start with the first
statement, showing that a certain cross-section 
is a measurable set. Fix $\tilde{\omega}_1 \in \Omega_1$.
If we can exhibit $A_{\tilde{\omega}_1}$ as the preimage 
of a measurable set under some measurable map with domain 
$(\Omega_2, \mathcal{A}_2)$, then we 
are done. Let's guess the map 
$$\iota: (\Omega_2, \mathcal{A}_2) \to (\Omega_1 \times \Omega_2, \mathcal{A}_1 \otimes \mathcal{A}_2)$$
given by $\iota(\omega_2) \mapsto (\tilde{\omega}_1, \omega_2)$. 
Then the preimage of the measurable set $A$ under this map
is $A_{\tilde{\omega}_1}$. But we still need to check
that $\iota$ is a measurable map. We can use Corollary 1.82 for that task.
We let $X_1(\omega_1, \omega_2) = \omega_1$ and $X_2(\omega_1, \omega_2) = \omega_2$, 
and then we note that $\mathcal{A}_1 \otimes \mathcal{A}_2$ is equal to 
the smallest sigma algebra such that $X_1$ is $\mathcal{A}_1 \otimes \mathcal{A}_2 - \mathcal{A}_1$
measurable and $X_2$ is $\mathcal{A}_1 \otimes \mathcal{A}_2 - \mathcal{A}_2$ measurable, 
a fact that is needed for applying Corollary 1.82. 

Note that $X_1 \circ \iota$ is constantly $\tilde{\omega}_1$, and is hence
$\mathcal{A}_2 - \mathcal{A}_1$ measurable. Also, 
$X_2 \circ \iota$ is just the identity map, and is hence
$\mathcal{A}_2 - \mathcal{A}_2$ measurable. Then 
Corollary 1.82 shows that $\iota$ is $\mathcal{A}_2 - \mathcal{A}_1 \otimes \mathcal{A}_2$ 
measurable. This proves the first statement. We leave the other statements 
for another life.

### $N^2$ copies of scalar Maxwell configurations versus Hermitian Maxwell Configurations

For each $1 \le i \le N$, let 
$$
\R^{|E_n^1|} \ni (y_e^{(ii)})_{e \in E_n} = y^{ii} \sim \frac{1}{Z_M(B_n)}
\exp \left( -\frac{1}{2} \sum_{p \in P(B_n)} (y^{ii}_p)^2 \right)
dl_{|E_n^1|}(y^{ii})
$$
be a random
scalar Maxwell configuration.
We instantiate $N^2- N$ other random scalar Maxwell
configurations notated, for each $1 \le j < k \le N$,
as
$z^{(ij)} = (z_e^{(ij)})_{e \in E_n} \in \R^{|E_n^1|}$
and $w^{(ij)} = (w_e^{(ij)})_{e \in E_n} \in \R^{|E_n^1|}$.
Here we are using the shorthand $\R^{|E_n^1|} := \R^{|E_n^1|} \times \{0\}^{E_n^0}$
and 
$$
dl_{|E_n^1|}(y^{ii}) = \left( \prod_{e \in E_n^1} dl_1(y^{ii}_e) \right) 
\otimes \left( \prod_{e \in E_n^0} d\text{Unif}_{\{0\}}(y^{ii}_e) \right),
$$
where $dl_1$ denotes 1-dimensional Lebesgue measure.
Each of the above configurations can be viewed
as $|E_n^1|$ dimensional Gaussian vectors. 

Assume that the above $N^2$ scalar Maxwell
configurations are independent of one another.
As a shorthand, let us write
$y = (y^{(ii)})_{1 \le i \le N}$, 
$z = (z^{ij})_{1 \le i < j \le N}$, and 
$w = (w^{ij})_{1 \le i < j \le N}$. 
Then by independence we have for 
the joint variable $(y,z,w) \in \R^{N^2 |E_n^1|}$
that 
\begin{equation}
\begin{gathered}
\mathbb P((y,z,w) \in A) = 
\int_A \frac{1}{Z_M(B_n)^{N^2}} 
\prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) d l_{|E_n^1|}(y^{ii})  \times \\ % end of first group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) d l_{|E_n^1|}(z^{ij}) \times \\ % end of second group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right) d l_{|E_n^1|}(w^{ij}),             % end of third group
\end{gathered}
\end{equation}
if $A \in \mathcal{B}_{\R^{N^2|E_n^1|}}$. 

Let $H = (H_e)_{e \in E_n} \in H(N)^{E_n^1}$ (where
$H(N)^{E_n^1}$ is shorthand for $H(N)^{E_n^1} \times \{0\}^{E_n^0}$) be a random 
Maxwell Hermitian configuration distributed according to the law
$$
\frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^1}(H)
$$
where 
$$
d\lambda_{E_n^1}(H) = \bigotimes_{e \in E_n^0} \text{Unif}_{\{0\}}
\otimes \bigotimes_{e \in E_n^1} d \lambda(H),
$$
where $d\lambda(H)$ denotes Lebesgue measure on $H(N)$.

Lemma. With $(y,z,w)$ and $H$ as above, 
we have 
$$
\mathbb P ((y,z,w) \in A) = \mathbb P(H \in \Psi_H^{|E_n^1|}(A))
$$
for all $A \in \mathcal{B}_{\R^{N^2|E_n^1|}}$.

#### Proof Attempt 1.

Proof. We begin with 
\begin{equation}
\begin{gathered}
\mathbb P(H \in \Psi_H^{|E_n^1|} (A)) = \frac{1}{Z_H(B_n)} \int_{\Psi_H^{|E_n^1|} (A)} 
 d\lambda_{E_n^1}(H) \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_{p_1} + H_{p_2} - H_{p_3} - H_{p_4} \rVert^2 \right). 
\end{gathered}
\end{equation}
Then we make the change of variable
$$
H_e = \Psi_H(y_e, z_e, w_e)
$$
for each $e \in E_n^1$.
Note that 
\begin{equation}
\begin{gathered}
\Psi_H(y_p, z_p, w_p) = \Psi_H \left( y_{p_1} + y_{p_2} - y_{p_3} - y_{p_4}, z_{p_1} + z_{p_2} - z_{p_3} - z_{p_4}, w_{p_1} + w_{p_2} - w_{p_3} - w_{p_4} \right)\\
= H_{p_1} + H_{p_2} - H_{p_3} - H_{p_4} = H_p.
\end{gathered}
\end{equation}
by linearity of $\Psi_H$.
Then with the change of variable we obtain
\begin{equation}
\begin{gathered}
\mathbb P(H \in \Psi_H^{|E_n^1|} (A)) = \frac{1}{Z_H(B_n)} \int_{A} 
 dl_{N^2|E_n^1|}(y,z,w) \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert \Psi_H(y_p, z_p, w_p) \rVert^2 \right). 
\end{gathered}
\end{equation}
Then since $\Psi_H$ is an isometry between $\R^{N^2}$ equipped with the Euclidean norm
and $H(N)$ equipped with the Hilbert Schmidt norm, we 
have
\begin{equation}
\begin{gathered}
\lVert \Psi_H(y_p,z_p,w_p) \rVert^2 = \lVert (y_{p_1} + y_{p_2} - y_{p_3} - y_{p_4}, z_{p_1} + z_{p_2} - z_{p_3} - z_{p_4}, w_{p_1} + w_{p_2} - w_{p_3} - w_{p_4}) \rVert^2 \\
= \sum_{i=1}^N (y^{ii}_{p_1} + y^{ii}_{p_2} - y^{ii}_{p_3} - y^{ii}_{p_4})^2 + 
\sum_{1 \le i < j \le N} (z^{ij}_{p_1} + z^{ij}_{p_2} - z^{ij}_{p_3} - z^{ij}_{p_4})^2 \\
+ \sum_{1 \le i < j \le N} (w^{ij}_{p_1} + w^{ij}_{p_2} - w^{ij}_{p_3} - w^{ij}_{p_4})^2.
\end{gathered}
\end{equation}
Then using Fubini's theorem for finite sums to 
exchange the sum over plaquettes $\sum_{p \in P(B_n)}$
with the sum over indices, such as $\sum_{1 \le i \le N}$, we obtain
\begin{equation}
\begin{gathered}
\sum_{p \in P(B_n)} \lVert \Psi_H(y_p, z_p, w_p) \rVert^2 = 
\sum_{i=1}^N \sum_{p \in P(B_n)} (y_{p}^{ii})^2 + \\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (z_p^{ij})^2 +\\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (w_p^{ij})^2.
\end{gathered}
\end{equation}
Then we notice that
\begin{equation}
\begin{gathered}
\exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert \Psi_H(y_p, z_p, w_p) \rVert^2 \right) = \prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right).
\end{gathered}
\end{equation}
As a result, 
\begin{equation}
\begin{gathered}
\mathbb P(H \in \Psi_H^{|E_n^1|} (A)) = \frac{1}{Z_H(B_n)} \int_{A} 
 dl_{N^2|E_n^1|}(y,z,w) \prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right), 
\end{gathered}
\end{equation}
where the last expression is 
equal to $\mathbb P((y,z,w) \in A)$ because 
our proof simultaneously showed
that 
\begin{equation}
\begin{gathered}
Z_H(B_n) = \int_{H(N)^{E_n^1}} d\lambda_{E_n^1}(H) \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right)\\
= \int_{\R^{N^2|E_n^1|}} dl_{N^2|E_n^1|}(t^1, \cdots, t^{N^2}) 
\prod_{i=1}^{N^2} 
\exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (t^i_p)^2 \right)\\
= \prod_{i=1}^{N^2} \int_{\R^{|E_n^1|}} dl_{|E_n^1|}(t^i) \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (t^i_p)^2 \right)\\
= Z_M(B_n)^{N^2}.
\end{gathered}
\end{equation}
This concludes the proof. QED.

#### Proof attempt 2.
Proof. 
We begin with
\begin{equation}
\begin{gathered}
\mathbb P((y,z,w) \in A) = 
\frac{1}{Z_M(B_n)^{N^2}}
\int_A
d l_{|E_n^1|N^2}(y,z,w)
\prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right)  \times \\ % end of first group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\ % end of second group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right).             % end of third group
\end{gathered}
\end{equation}
Then we make the change of variable
$$(\Psi_H^{-1}(H_e))_{e \in E_n^1} = \left( \Psi_H^{|E_n^1|} \right)^{-1} (H) = (y,z,w),$$
which means that for each $e \in E_n^1$, we have
$$
(H_e)^{jk} = (\Psi_H(y_e, z_e, w_e))^{jk} = \begin{cases}y_e^{j j} & \text { if } j=k, \\
\left(z_e^{j k}+\mathrm{i} w_e^{j k}\right) / \sqrt{2} & \text { if } j<k, \\
\left(z_e^{k j}-\mathrm{i} w_e^{k j}\right) / \sqrt{2} & \text { if } j>k,\end{cases}
$$
and for $e \in E_n^0$ we have $H_e = 0 \in H(N)$.
Then
\begin{equation}
\begin{gathered}
\mathbb P((y,z,w) \in A) = 
\frac{1}{Z_M(B_n)^{N^2}}
\int_{\Psi_H^{|E_n^1|}(A)}
d l_{|E_n^1|N^2}(y,z,w)
\prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right)  \times \\ % end of first group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\ % end of second group
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right).             % end of third group
\end{gathered}
\end{equation}



## June 3, 2026

Let $H = (H_e)_{e \in E_n} \in H(N)^{E_n}$ be a random 
Hermitian configuration distributed according to the law
$$
\frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H)
$$
where 
$$
d\lambda_{E_n^0}(H) = \bigotimes_{e \in E_n^0} \text{Unif}_{\{0\}}
\otimes \bigotimes_{e \in E_n^1} d \lambda(H),
$$
where $d\lambda(H)$ denotes Lebesgue measure on $H(N)$.
In particular, let 
$$
\Psi_H: \R^{N^2} \to H(N)
$$
be the map
\begin{equation}
\begin{gathered}
(y,z,w) = (\left(y_{j j}\right)_{1 \leq j \leq N}, 
\left(z_{j k}\right)_{1 \leq j<k \leq N}, \left(w_{j k}\right)_{1 \leq j<k \leq N}) \\
\mapsto \begin{bmatrix}
y_{11} & & & \frac{z_{jk} + iw_{jk}}{\sqrt{2}} \\
 & \ddots & &  \\
 & &  &  \\
\frac{z_{jk} - iw_{jk}}{\sqrt{2}} & & & y_{NN}
\end{bmatrix}.
\end{gathered}
\end{equation}

Then $d\lambda(H)$ is equal to 
the pushforward of $l_{N^2}$, $N^2$-dimensional
Lebesgue measure, by the map $\Psi_H$: 
$$
\lambda = \Psi_H^* l_{N^2} = l_{N^2} \circ \Psi_H^{-1}.
$$
In particular, if $f$ is some integrable function of $H \in H(N)$, 
then 
$$
\int f(H) d\lambda(H) = \int f(\Psi_H(y,w,z)) dl_{N^2}(y,w,z).
$$

Let $B \in \mathcal{B}(H(N)^{E_n})$ be a Borel 
subset of Hermitian configuration space. (Or do 
we need to take a cylinder set?)
Then 
$$
\mathbb P(H \in B) = \int_{B} \frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H).
$$
(How do you integrate against uniform measure on the $E_n^0$ edges?)
Fix $p \in P(B_n)$.
Then 
$$
H_p = H_{p_1} + H_{p_2} - H_{p_3} - H_{p_4},
$$
where the $p_i$ are the edges comprising the plaquette
$p$. We have separate parameters $(y_{p_i}, z_{p_i}, w_{p_i})$ 
for each of the four Hermitian matrices associated to the plaquette.
Note that $y_{p_i} \in \R^N$, $z_{p_i} \in \R^{N(N-1)/2}$, and $w_{p_i} \in \R^{N(N-1)/2}$. 
We write
$$
H_{p_i} = \Psi_H(y_{p_i}, z_{p_i}, w_{p_i})
$$
for each plaquette edge $p_i$. Then by linearity of $\Psi_H$, we have
$$
H_{p} = \Psi_H \left( y_{p_1} + y_{p_2} - y_{p_3} - y_{p_4}, z_{p_1} + z_{p_2} - z_{p_3} - z_{p_4}, w_{p_1} + w_{p_2} - w_{p_3} - w_{p_4} \right). 
$$

Then since $\Psi_H$ is an isometry between $\R^{N^2}$ equipped with the Euclidean norm
and $H(N)$ equipped with the Hilbert Schmidt norm, we 
have
\begin{equation}
\begin{gathered}
\lVert H_p \rVert^2 = \lVert (y_{p_1} + y_{p_2} - y_{p_3} - y_{p_4}, z_{p_1} + z_{p_2} - z_{p_3} - z_{p_4}, w_{p_1} + w_{p_2} - w_{p_3} - w_{p_4}) \rVert^2 \\
= \sum_{i=1}^N (y^{ii}_{p_1} + y^{ii}_{p_2} - y^{ii}_{p_3} - y^{ii}_{p_4})^2 + 
\sum_{1 \le i < j \le N} (z^{ij}_{p_1} + z^{ij}_{p_2} - z^{ij}_{p_3} - z^{ij}_{p_4})^2 \\
+ \sum_{1 \le i < j \le N} (w^{ij}_{p_1} + w^{ij}_{p_2} - w^{ij}_{p_3} - w^{ij}_{p_4})^2
\end{gathered}
\end{equation}
Then we write
\begin{equation}
\begin{gathered}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 =
\sum_{p \in P(B_n)} \sum_{i=1}^N (y^{ii}_{p_1} + y^{ii}_{p_2} - y^{ii}_{p_3} - y^{ii}_{p_4})^2 + \\
\sum_{p \in P(B_n)} \sum_{1 \le i < j \le N} (z^{ij}_{p_1} + z^{ij}_{p_2} - z^{ij}_{p_3} - z^{ij}_{p_4})^2 + \\
\sum_{p \in P(B_n)} \sum_{1 \le i < j \le N} (w^{ij}_{p_1} + w^{ij}_{p_2} - w^{ij}_{p_3} - w^{ij}_{p_4})^2 \\
= \sum_{i=1}^N \sum_{p \in P(B_n)} (y^{ii}_{p_1} + y^{ii}_{p_2} - y^{ii}_{p_3} - y^{ii}_{p_4})^2 + \\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (z^{ij}_{p_1} + z^{ij}_{p_2} - z^{ij}_{p_3} - z^{ij}_{p_4})^2 + \\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (w^{ij}_{p_1} + w^{ij}_{p_2} - w^{ij}_{p_3} - w^{ij}_{p_4})^2 \\
= \sum_{i=1}^N \sum_{p \in P(B_n)} (y_{p}^{ii})^2 + \\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (z_p^{ij})^2 +\\
\sum_{1 \le i < j \le N} \sum_{p \in P(B_n)} (w_p^{ij})^2.
\end{gathered}
\end{equation}
Then we have
\begin{equation}
\begin{gathered}
\exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) = \prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right).
\end{gathered}
\end{equation}
Next we have
\begin{equation}
\begin{gathered}
d\lambda_{E_n^0}(H) = \prod_{e \in E_n^1} d\lambda(H_e) \\
= \prod_{e \in E_n^1} d\Psi_H^* l_{N^2}(H_e)
\end{gathered}
\end{equation}
Fixing an edge $e \in E_n^1$, we have 
\begin{equation}
\begin{gathered}
\int f(H_e) d\Psi_H^* l_{N^2}(H_e) = \int f(\Psi_H(y_e, z_e, w_e)) dl_{N^2}(y_e, z_e, w_e),
\end{gathered}
\end{equation}
so if we iterate this by freezing all other edge variables 
one at a time, we obtain
\begin{equation}
\begin{gathered}
\int \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H) = \\
\int \prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right) \prod_{e \in E_n^1} dl_{N^2}(y_e, z_e, w_e)
\end{gathered}
\end{equation}
But if we integrate first over the edges and then over the 
$N^2$ dimensions of $\R^{N^2}$, meaning use
\begin{equation}
\begin{gathered}
\prod_{e \in E_n^1} dl_{N^2}(y_e, z_e, w_e) = 
\prod_{1 \le i \le N} \prod_{e \in E_n^1} dl_1(y_e^{ii}) \otimes \\
\prod_{1 \le i < j \le N} \prod_{e \in E_n^1} dl_1(z_e^{ij}) \otimes \\
\prod_{1 \le i < j \le N} \prod_{e \in E_n^1} dl_1(w_e^{ij}),
\end{gathered}
\end{equation}
then we have 
\begin{equation}
\begin{gathered}
\int \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H) = \\
\prod_{1 \le i \le N} \int \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \prod_{e \in E_n^1} dl_1(y_e^{ii}) \times \\
\prod_{1 \le i < j \le N} \int \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \prod_{e \in E_n^1} dl_1(z_e^{ij}) \times \\
\prod_{1 \le i < j \le N} \int 
\exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right) \prod_{e \in E_n^1} dl_1(w_e^{ij}) \\
\end{gathered}
\end{equation}

I want to see that the joint law of $N^2$ independent lattice Maxwell 
configurations is the same as the law of a Hermitian configuration
distributed according to the law
$$
\frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H).
$$
I suppose that $N^2$ indepdendent lattice Maxwell configurations
would be in $(\R^{N^2})^{E_n^1}$, where it is $E_n^1$ because 
the $E_n^0$ edges are deterministically set to 0. 

For each $1 \le i \le N$, let $(y_e^{ii})_{e \in E_n}$ be a random lattice Maxwell configuration, 
taking values in $\R^{E_n^1}$. And for each $1 \le i < j \le N$, let
$(z_e^{ii})_{e \in E_n}$ and $(w_e^{ii})_{e \in E_n}$ be random lattice
Maxwell configurations, also taking values in $\R^{E_n^1}$.

What is the definition of the joint law of these random variables?
It is a probability measure $P$ on $(\R^{N^2})^{E_n}$ 
satisfying
$$
\mathbb P((y^{ii}, z^{ij}, w^{ij}) \in A) = P(A).
$$
for any Borel subset $A$ in the Borel sigma algebra
on $(\R^{N^2})^{E_n}$.

$\Psi_H: \R^{N^2} \to H(N)$ is an isometry, so it is 
also bi-continuous. Therefore $\R^{N^2}$ and $H(N)$ are 
homeomorphic, so their Borel Sigma algebras should be 
related to each other.
And if we write down the product map
$\prod_{e \in E_n} \Psi_H$, then we have a homeomorphism 
between $H(N)^{E_n}$ and $(\R^{N^2})^{E_n}$.

:::{#lem-thm1.78Klenke}

## Theorem 1.78 in @Klenke

Let $(\Omega', \mathcal{A}')$ be a measurable space and let 
$\Omega$ be a non-empty set. Let $X: \Omega \to \Omega'$ be
a map. The preimage 
$$
X^{-1}(\mathcal{A}') := \{ X^{-1}(A') : A' \in \mathcal{A}' \}
$$
is the smallest $\sigma$-algebra with respect to which $X$
is measurable. We say that $\sigma(X):= X^{-1}(\mathcal{A}')$ is 
the $\sigma$-algebra on $\Omega$ that is generated by $X$.
:::

Let us identify $(\R^{N^2})^{E_n}$ with $\R^{N^2|E_n|}$. Let us also 
identify $H(N)^{E_n}$ with $H(N)^{|E_n|}$. Note that 
$$(H(N)^{|E_n|}, \mathcal{B}_{H(N)^{|E_n|}})$$
is a measurable space, where $\mathcal{B}_{H(N)^{|E_n|}}$ denotes the 
Borel sigma algebra on $H(N)^{|E_n|}$. If $\mathcal{B}_{\R^{N^2|E_n^1}}$ 
denotes the Borel sigma algebra on $\R^{N^2|E_n^1|}$, does it follow
that 
$$
\sigma(\prod_{e \in E_n} \Psi_H) = \mathcal{B}_{\R^{N^2|E_n^1}}?
$$

Or an easier question is as follows. Consider the measurable space $(H(N), \mathcal{B}_{H(N)})$.
Does it follow that 
$$
\sigma(\Psi_H) = \mathcal{B}_{\R^{N^2}}?
$$
Note that $\mathcal{B}_{\R^{N^2}}$ is the intersection 
of all sigma algebras which contain the standard topology on $\R^{N^2}$
as a subcollection. Meanwhile, the left hand side 
$\sigma(\Psi_H)$ is the intersection of all sigma algebras $\sigma_*$ 
with the proporty that $\Psi_H: (\R^{N^2}, \sigma_*) \to (H(N), \mathcal{B}_{H(N)})$ is measurable.

There is likely an easy direction based on the above two sentences. 
Here is a question. 
If $\sigma_*$ is a sigma algebra on $\R^{N^2}$ which contains
the standard topology $\tau_{\R^{N^2}}$ as a subcollection, does it 
follow that $\Psi_H: (\R^{N^2}, \sigma_*) \to (H(N), \mathcal{B}_{H(N)})$ is measurable?
If the answer is yes, then it would mean 
$\mathcal{B}_{\R^{N^2}} \supset \sigma(\Psi_H)$ 
because then $\mathcal{B}_{\R^{N^2}}$ would be an intersection 
over a subfamily of the family which $\sigma(\Psi_H)$ is 
an intersection of. And the answer is indeed yes 
because it is enough for measurability of the map 
$\Psi_H: (\R^{N^2}, \sigma_*) \to (H(N), \mathcal{B}_{H(N)})$
to check that 
$\Psi_H^{-1}(B) \in \sigma_*$ for every open set $B \in \mathcal{B}_{H(N)}$, 
which does hold by continuity of the map $\Psi_H$.
Thus, 
$$
\mathcal{B}_{\R^{N^2}} \supset \sigma(\Psi_H). 
$$

But $\Psi_H^{-1}(\tau_{H(N)}) = \tau_{\R^{N^2}}$ because $\Psi_H$ is 
a homeomorphism, so every sigma algebra $\sigma_*$ with the property that
$\Psi_H: (\R^{N^2}, \sigma_*) \to (H(N), \mathcal{B}_{H(N)})$ is measurable
must contain $\tau_{\R^{N^2}}$ as a subcollection. Hence, 
$$
\mathcal{B}_{\R^{N^2}} \subset \sigma(\Psi_H). 
$$

Let $H \in H(N)^{|E_n|}$ be a random Hermitian configuration
drawn according to the measure
$$
\frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H).
$$
This means that 
$$
\mathbb P(H \in A) = \int_A \frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H).
$$
for any Borel subset $A \in \mathcal{B}_{H(N)^{|E_n^1|}}$.

Note that
$$
\prod_{e \in E_n} \Psi_H: (\R^{N^2})^{|E_n|} \to H(N)^{|E_n|}. 
$$
See [Product Map](https://planetmath.org/productmap). 
Let's just assume without proof that
$$
\sigma(\prod_{e \in E_n} \Psi_H) = \mathcal{B}_{\R^{N^2|E_n|}}
$$

We claim based on the above computations that 

\begin{equation}
\begin{gathered}
\int_A \frac{1}{Z_H(B_n)} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} \lVert H_p \rVert^2 \right) d\lambda_{E_n^0}(H) = \\
\frac{1}{Z_H}
\int_{(\prod_{e \in E_n} \Psi_H)^{-1}(A)} 
 \prod_{1 \le i \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (y_{p}^{ii})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (z_p^{ij})^2 \right) \times \\
\prod_{1 \le i < j \le N} \exp \left( - \frac{1}{2}
\sum_{p \in P(B_n)} (w_p^{ij})^2 \right) \prod_{e \in E_n^1} dl_{N^2}(y_e, z_e, w_e).
\end{gathered}
\end{equation}

But now I think we can't proceed to break up the integral 
into products, so we might have to resort to cylinder sets. 
But why do we want to break up the integral into products anyways?
I want to obtain something like 
$$
\mathbb P(H \in A) = \mathbb P((y,z,w) \in (\prod_{e \in E_n} \Psi_H)^{-1}(A)). 
$$
for all $A$ Borel subsets of $H(N)^{E_n}$, 
where $(y, z, w)$ are $N^2$ lattice Maxwell fields. 
This would show that the law of $N^2$ copies of 
lattice Maxwell fields is the pushforward or pullback (which one?)
of the law of Hermitian lattice theory. 

If pushforward, then we'd have
$$
(y,z,w)^* \mathbb P = (\prod_{e \in E_n} \Psi_H)^* (H^* \mathbb P). 
$$
That would mean
$$
\mathbb P ((y,z,w) \in A) = (H^* \mathbb P)((\prod_{e \in E_n} \Psi_H)^{-1}(A)) = \mathbb P(H \in (\prod_{e \in E_n} \Psi_H)^{-1}(A)),
$$
which is not what we want. 
If pullback, then we'd have
$$
\mathbb P ((y,z,w) \in A) = (H^* \mathbb P)(\prod_{e \in E_n} \Psi_H(A)) = \mathbb P(H \in \prod_{e \in E_n} \Psi_H(A)), 
$$
which is better. 

:::{#lem-HermitianMaxwellComparison}

The joint law $((t^{(i)})_{i=1}^{N^2})^* \mathbb P$ of $N^2$ indepedent lattice
Maxwell scalar configurations on $(\R^{N^2})^{|E_n|}$
is equal to the pullback of the law 
$H^* \mathbb P$ of Hermitian 
lattice Maxwell theory by the map $\prod_{e \in E_n} \Psi_H$. 

:::

So we are showing that two proability laws are equal to eachother.

Let $X_1, \cdots, X_n$ be $n$ independent real random variables
with densities $f_1: \R \to \R$, $f_2: \R \to \R$, $\cdots,$ $f_n: \R \to \R$
repsectively.

Then the joint density function of the joint variable
$(X_1, \cdots, X_n)$ is $f(x_1, \cdots, x_n) = 
f_1(x_1)f_2(x_2) \cdots f_n(x_n)$. This means that for any 
Borel subset $A \in \mathcal{B}_{\R^n}$, we have
$$
\mathbb P(X \in A) = \int_A f_1(x_1)f_2(x_2) \cdots f_n(x_n) dx_1 \cdots dx_n.
$$

Let $X_1: \Omega \to \R^2$ and $X_2: \Omega \to \R^3$
with densities $f_1: \R^2 \to \R$ and $f_2: \R^3 \to \R$
respectively.
If $X_1$ and $X_2$ are independent, then the 
joint density function of $(X_1,X_2)$ is given 
by $f(x_1, x_2, x_3, x_4, x_5) = f_1(x_1, x_2) f_2(x_3, x_4, x_5)$.
How do you know this?

For each $1 \le i \le N^2$, 
Let $t^{(i)} \in \R^{|E_n|}$ be distributed according 
to lattice Maxwell theory. 
Then for each $i$, the probability density function 
of $t^{(i)}$ is 
$$\frac{1}{Z_M(B_n)} \exp(-\frac{1}{2} M_n(t^{(i)})).$$



## June 2, 2026

Let $t \in \R^{E_n}$ be distributed according
to the probability distribution
$$
\frac{1}{Z_M(B_n)} \exp(-\frac{1}{2} M_n(t)) dl_{E_n^0, 1}(t),
$$
where 
$$dl_{E_n^0, 1}(t) = \bigotimes_{e \in E_n^0} \text{Unif}_{\{0\}}(t_e) \otimes 
\bigotimes_{e \in E_n^1} dl_1(t_e).
$$
This probability distribution is called 
lattice Maxwell theory on $B_n$ with boundary value 0.
In other words, $t_e$ is determinstically equal to 0
when $e \in E_n^0$ and is otherwise a random real number
with distribution $\mathcal{N}(\mu_e, \sigma_e)$, 
where $\mu_e$ and $\sigma_e$ can be computed from $M_n$.
 
On the other hand, a Hermitian matrix $H \in H(N)$ can be 
parameterized using $N^2$ variables by writing the 
$(j, k)^{\text {th }}$ entry of $H$ as
$$
x_{j k}= \begin{cases}y_{j j} & \text { if } j=k, \\ \left(z_{j k}+\mathrm{i} w_{j k}\right) / \sqrt{2} & \text { if } j<k, \\ \left(z_{k j}-\mathrm{i} w_{k j}\right) / \sqrt{2} & \text { if } j>k,\end{cases}
$$
as illustrated by
$$
\begin{bmatrix}
y_{11} & & & \frac{z_{jk} + iw_{jk}}{\sqrt{2}} \\
 & \ddots & &  \\
 & &  &  \\
\frac{z_{jk} - iw_{jk}}{\sqrt{2}} & & & y_{NN}
\end{bmatrix}.
$$

Then the $N^2$ parameters are $\left(y_{j j}\right)_{1 \leq j \leq N},\left(z_{j k}\right)_{1 \leq j<k \leq N}$, and $\left(w_{j k}\right)_{1 \leq j<k \leq N}$.

Let $(t^{(jk)})_{1 \le j \le k \le N}$ be $N^2$
mutually independent lattice Maxwell fields, arranged 
in some arbitrary way. That is, for each $j,k$ with 
$1 \le j \le k \le N$, we have that $(t_e^{(jk)})_{e \in E_n}$
has the law above. 

Based on the definition of Lebesgue measure on $H(N)$, one sees
that the law of 
$H(t^{(jk)})$ is just the joint law of the $t^{(jk)}$, and is 
thus just the $N^2$ fold product of the law of scalar Maxwell theory
by independence of the $t^{(jk)}$.
