---
title: "List of results from CQFT 2"
bibliography: references.bib
---

On this page, I will learn about the contents of
@BrenneckeCQFT via the method of lists. 

I apologize to Jaques Ellul for 
performing this technisized extraction of information. 

### Chapter 1: Classical Mechanics

:::{.callout-note title="Result: Hamilton's equations from Classical Mechanics"}
$$
\frac{dx}{dt} = \nabla_p H, \hspace{0.5cm} \frac{dp}{dt} = - \nabla_x H
$$
:::

:::{.callout-note title="Maxwell's equations"}
$$
\nabla \cdot E = \rho, \hspace{0.5cm} \nabla \times E = - \frac{1}{c} \partial_t B,
$$
$$
\nabla \cdot B = 0, \hspace{0.5cm} \nabla \times B = \frac{1}{c}(\partial_t E + j)
$$
:::

:::{.callout-note title="Charge and Current Densities as Distributions"}
$$
t \mapsto \rho(t,x) = e \delta_{x(t)} \in \mathcal{D}'(\mathbb R^3)
$$
and 
$$
t \mapsto j(x,t) = e \delta_{x(t)} \frac{dx}{dt}(t) \in \mathcal{D}'(\mathbb R^3, \mathbb R^3)
$$
:::

:::{.callout-note title="Observables are conserved when Poisson bracket with Hamiltonian vanishes"}
Suppose $F \in C^{\infty}(\mathcal{P})$ and that $\{F,H\} = 0$. Then 
$$
\frac{d}{dt} F \circ (x(t), p(t)) = 0.
$$
:::
In this case, $F$ is called a conserved quantity under 
the Hamiltonian dynamics. 

:::{.callout-note title="Criterion to ensure vanishing of Poission Bracket with Hamiltonian"}
If $F \in C^{\infty}(\mathcal{P})$ is invariant 
under the Hamiltionian flow associated to 
the Hamiltonian vector field $X_H$, meaning that 
$$
\Phi_{X_H}(t,\cdot)^*F = F,
$$
then 
$\{F,H\} = 0$.
:::

:::{.callout-note title="Hamiltionian vector field flows are coordinate transformations"}
Let $F \in C^{\infty}(\mathcal{P})$ be an observable (possibly the Hamiltonian). 
Then the flow, $\Phi_{X_H}(t, \cdot)$, of the Hamiltonian vector field $X_H = \mathbf{J} \nabla H$
is equal to a canonical transformation $\phi \in C^{\infty}(\mathcal{P}, \mathbb R^{2n})$
for any time $t$.
:::

:::{.callout-note title="Symmetry of Hamiltionian implies observable is conserved"}
Let $F \in C^{\infty}(\mathcal{P})$. 
If the Hamilitionian $H$ is invariant under the flow generated by $X_F = \mathbf{J} \nabla F$, i.e., 
$$
H = \Phi_{X_F}(t, \cdot)^* H,
$$
then $\{F,H\} = 0$.
:::

### Chapter 2.1: Mathematical Interlude: Locally Convex Topological Vector Spaces

:::{.callout-note title="What is a locally convex topological vector space?"}
Let $X = (X,\mathbb K, +, \cdot, \tau)$ be a topological vector space, which is the data of 
a vector space $(X, \mathbb K, +, \cdot)$ together with a topology $\tau$
of open subsets of $X$ such that 
$+$ (addition) and $\cdot$ (scalar multiplication)
are continuous (from the product topology in the case of addition). 

We don't need any new data to say that $X$ is locally convex, but
there must be a local base $\mathcal{B}$ whose elements are convex. 
:::

:::{.callout-note title="What is a local base at 0?"}
Let $(X,\tau)$ be a topological vector space. 
A local base at $0$, call it $\mathcal{B}$, is the following:
$\mathcal{B} \subset \tau$, $0 \in B$
for all $B \in \mathcal{B}$, and 
for any open subset $A$ containing $0$, 
there exists some $B \in \mathcal{B}$ such that $B \subset A$.
:::

:::{.callout-note title="For locally convex definition, only need local base at 0."}
If $(X,\mathbb K, \tau)$ is a topological vector space with 
a local base at $0$, $\mathcal{B}$, then $\tau$ is completely 
determined by $\mathcal{B}$.
:::

:::{.callout-note title="What is a Semi-norm?"}
A semi-norm on a vector space $X$ is a real-valued
function $p: X \to [0,\infty)$ such that 
$p(x+y) \le p(x) + p(y)$ and $p(\lambda x) = |\lambda|p(x)$ for all $x,y \in X$
and $\lambda \in \mathbb K$. In other words, $p$ would be a norm, other than 
for the possibility that $p(x) = 0$ when $x \ne 0$.
:::

:::{.callout-note title="Consider a family of seminorms. When is it separating?"}
Suppose $\mathcal{P} = (p_n)_{n \in \mathbb N}$ is a family of 
seminorms, where $p_n: X \to [0,\infty)$ is a real-valued function on a 
$\mathbb K$-vector space for all $n$. Then $\mathcal{P}$ is said to 
be separating if for any $x \ne 0$ in $X$, there is some $p \in \mathcal{P}$
such that 
$p(x) \ne 0$. In particular, 
when two elements $f, g \in X$ are distinct, 
in that $f - g \ne 0$, then 
$\mathcal{P}$ will know this, in the sense that 
at least one $p$ thinks that 
$p(f-g) \ne p(0) = 0$.
:::

For example, consider the family of the Schwartz seminorms 
$|\cdot|_{\alpha, \beta} = \sup_{x \in \mathbb R^n} |(x^{\alpha} \partial^{\beta} \varphi)(x)|$, 
indexed by multi indices $\alpha$, $\beta$. 
Some of these
seminorms might not be able to tell the 
difference between two Schwartz functions 
$f$ and $g$ in the sense that
$f - g \ne 0$ and yet 
$|f-g|_{\alpha, \beta} = 0$. 
For instance, polynomials, after taking enough 
derivatives, evaluate to the zero function, so they 
would vanish under the Schwartz semi norms for 
high enough $|\beta|$. Moreover, the $L^2$ norm
does not separate functions, but it does 
separate equivalence classes of functions.

:::{.callout-note title="The space of Temperered Distributions arising as dual space of Schwarz functions"}
The Schwarz functions on $\mathbb R^n$, denoted $\mathcal{S}(\mathbb R^n)$,
with function addition and scalar multiplication, 
and with a locally convex topology generated by
the separating family of seminorms $|\cdot|_{\alpha,\beta}$, 
is a locally convex topological vector space.

The dual space of $\mathcal{S}(\mathbb R^n)$, denoted $\mathcal{S}'(\mathbb R^n)$ and
called the space of tempered distributions,
is the vector space of continuous (in the sense of the convex topology on Schwartz function space)
linear functionals $\Lambda: \mathcal{S}(\mathbb R^n) \to \mathbb C$
under pointwise addition and scalar multiplication. 
Furthermore, this dual space comes with a topology that 
turns the space of tempered distributions from merely 
a vector space into a locally convex topological vector space. 
It is the topology generated by 
the family of seminorms $(\text{eval}_f)_{f \in S(\mathbb R^n)}$
where $\text{eval}_f: \mathcal{S}'(\mathbb R^n) \to [0,\infty)$ 
is defined via
$$
\text{eval}_f(\Lambda) = |\Lambda(f)|
$$
for all test functions $f \in \mathcal{S}(\mathbb R^n)$.
This is precisely the weak* topology $\sigma(X^*,X) = \sigma(S'(\mathbb R^n), S(\mathbb R^n))$.
:::

### Chapter 2.2: Distributions and Tempered Distributions

:::{.callout-note title="How do you identify a function by duality?"}
Given a function $f$, we identify $f$ with 
$$
\Lambda_f: \text{Test Functions} \to \mathbb K, \hspace{0.5cm} \varphi \mapsto \int f \varphi.
$$
:::

:::{.callout-note title="What is irregularity for a distribution?"}
The Dirac distribution, centered at a point $x \in \Omega \subset \mathbb R^n$, 
is the prime example of an "irregular" distribution, because there is 
no "nice" function $f$ such that 
$\delta_x = f (= \Lambda_f)$ in the sense of duality/distributions. 
:::

:::{.callout-note title="What is a singularity in the context of the theory of distributions?"}
Consider the Dirac distribution $\delta_{x_0}$. 
Then you can define heuristally $\delta_{x_0}(x \ne x_0) = 0$ and $\delta_{x_0}(x_0) = \infty$, 
and in this case, there is a singularity at $x_0$.
:::

:::{.callout-note title="What is the regularity of tempered distributions?"}
In short, tempered distributions correspond (via duality) to 
(weak) derivatives of polynomially bounded continuous functions. 

The precise statement is as follows. Let $\Lambda \in \mathcal{S}'(\mathbb R^n)$.
Then there exists a polynomially bounded
and continuous function $f \in C(\mathbb R^n)$ such that
$$\partial^{\alpha}f = \Lambda,$$
which, means that
$$\Lambda(\cdot) = \partial^{\alpha} \Lambda_f(\cdot) := (-1)^{|\alpha|} \Lambda(f \partial^{\alpha}(\cdot)),
$$
which means the for any Schwartz function $\phi \in \mathcal{S}(\mathbb R^n)$, 
$$
\Lambda(\phi) = (-1)^{|\alpha|} \int_{\mathbb R^n} dx f(x) (\partial^{\alpha} \phi)(x)
$$
:::

(I got confused by $(\partial^{\alpha} \phi)(x)$, so for that just 
remember that for real-valued functions, the partial derivative
at a point is just a number, not a linear map.)

For example, the Dirac delta function centered at $0$, as a tempered distribition 
on $\mathbb R$, is the 2nd weak/distributional derivative of
$\max{(0,x)}$. This is because $\delta_0$ 
is the weak derivative of the Heaviside function $H(x) = \chi_{[0,\infty]}$, 
which is the weak derivative of $\max{(0,x)}$.