---
title: "Twitter-like feed"
---

<!--
This file is edited from mobile.
Do not overwrite without pulling first.
-->

### April 10, 2026

Idea to find formula. 
Need Lie algebra of SU(2). 
Reduce leading term of log of partition
function of the coupled theory 
to integrals over small balls.
Can we use the axial gauge? 
That is, is the Wilson action
coupled with the Higgs mechanism
going to behave nicely with regards
to gauge transforms?
Replace integration over Lie group
to integration over Lie algebra. 
This is where you get the edge count 
terms and the Radon Nikodym correction term.
Do we have a formula for
the volume of SU(2) as a submanifold?
Which Maxwell action will do the trick?
Does the coupling impact the leading order
approximation?
To guess the formula, can't we just
assume that the Maxwell theory 
describes the leading order behavior?

### April 9, 2026

Can axial guage fixing be viewed 
as a change of coordinates in analogy to 
a rotation in R3? I'm thinking of the rotations
used in the Gaussian integral computation in
Friedman's book. And I'm also thinking
of the change of measure formula in 
measure theory. 

### March 25, 2026

For next Thursday I'm supposed to 
present Lemma 10.2 and Lemma 13.1. 
Also, I'm wondering if the characterization
of the lattice Maxwell action as a difference
of Dirichlet forms gives an alternative
proof of Lemma 13.1. But for that I'd 
need an upper bound on the 2nd term, 
which would not be a bottom of the 
spectrum thing. 

### February 20, 2026

The matrix of the form 
in section 2 of Chatterjee has a 
determinant which is invariant under
a change of the ordering of
the elements of the edge set. 
If you permute the edge set,
this permutation corresponds to a 
sequence of transpositions. Each 
transposition corresponds to 
swapping two rows then two columns. When you
swap two rows, the determinant changes by 
a factor or negative one. Swapping 
the corresponding columns changes the
determinant back to what it was originally.
This shows the the determinant is well defined
regardless of the choice of 
ordering of the edges. 

### February 3, 2026

Today in my lecture we learned about the
equivalence between Green's function
G(x,y) on a graph being finite and 
a graph being transient, meaning that 
a random walk won't come back infinitely
often to the same point. I also thought 
about how G(x,y) can be thought of as the
total heat seen by the point x, as you
propogate a heat flow with initial heat data
defined by a value of 1 at y and a value 
of 0 everywhere else.

Note that for dimension greater than 2,
the infinite volume lattice is transient,
meaning that Green's function on the 
infinite volume lattice is finite. 

There was also a result about transience for 
tree graphs. I wonder if I can use that 
result in the context of the axial graph 
in lattice gauge theory. 

Balaban wrote a paper about 
Green's functions, and this paper led to
his ultraviolet stability proof. 
Green's function in the sense of 
distributions is formally speaking 
the two point quantum field expecation,
where you formally insert a dirac delta 
into the quantum field distribution. 

Brennecke saw that something in the 
Chatterjee paper is related to a 
differential operator. Also Balaban defined 
a 2nd order differential operator on the 
lattice. Also there is the Poincare inequality 
in Section 10 of the Chatterjee paper. 
I wonder if there is a bridge between
Green's functions and these operators. 
And between Dirichlet forms on graphs and
these differential operators. Recalling 
the graph Laplacian, you just take local
differences of the function argument. 

Also, there is the so called Yang Mills
heat flow in the continuum. What is
the Yang Mill's heat flow on a lattice?
The heat kernel for a Laplacian on a graph
is just e to the negative t times L. It is
the heat semigroup. 

Oh another interesting thing from today
was that the Laplace transform 
provided a bridge between the land of 
resolvents and the land of heat semigroups
or heat equation or Green's functions. 
As long as alpha is in the resolvent set,
meaning that alpha cannot be an eigenvalue
of the Laplace operator, or that alpha 
lies below the smallest eigenvalue, then 
you can consider the inverse 
map (L+alpha)^{-1} and do spectral
stuff with it. 


### January 6, 2025

When the coupling constant 
of U(N) lattice gauge theory is
small, then beta is big. 
When beta is big, the format of the
Yang mills probability density 
forces the Wilson action
to be very small if there
is to be any probability mass
associated to a given configuration.
The Wilson action being small 
means that most unitary matrices
are equal to the identity matrix.
Matrices mostly being equal to
identity matrices implies
that parallel transporting
along plaquettes does not do
anything. So the gauge field has 
no effect. I think that the gauge
field having little effect 
and the coupling constant being
small are related concepts. 
By analogy, smallness of the coupling
constant for gravity means that 
gravity has little role. 

I was previously confused because
I noticed that when the coupling constant 
is large, then the Yang Mills gauge measure
is just a product Haar measure. 
I figured product Haar measure means
that there is no interaction, a contradiction
to the coupling constant being large. 
Perhaps the reason that this is
not a contradiction is that
unitary matrices under Haar measure
are not concentrated near the identity matrix,
so during parallel transport, the gauge 
field plays a bigger role. And the gauge field 
taking stronger role fits with 
the coupling constant being larger. 

### December 24, 2025 

Conditional probabilities are where
you fix some prior knowledge/variables and 
then you ask about the probability 
for the remaining variables.

That seems like the right framework for
axial gauge fixing. You fix the variables
for the tree edges, then figure out
the rest of the variables. 

### December 25, 2025

The log beta term in the formula for the
free energy is related to 
the 1/beta smallness of the 
Wilson action.

Also, even though the math of cqft is
very eclectic and broad, it also
feels like a niche field. At least
I get that feeling when looking 
at one of the early papers by Fröhlich
and Brydges. 


